version: 2
jobs:
  build-website:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.13.1
    steps:
      - checkout
      - run:
          name: Building
          command: |
            cd website 
            yarn install --frozen-lockfile
            yarn build
      - run:
          name: Ping FeaturePeek
          command: bash <(curl -s https://peek.run/ci)
workflows:
  version: 2
  build:
    jobs:
      - build-website:
          filters:
            branches:
              ignore:
                - gh-pages
